### ISSUE TITLE
Sending PATCH request: Received response code: 400

### ISSUE THREAD

**Issue by qdm12** [peter-evans/dockerhub-description#11]
Hello, thanks for the nice tool first 👍 

However, on [my repository](https://github.com/qdm12/private-internet-access-docker), using [this workflow file](https://github.com/qdm12/private-internet-access-docker/blob/master/.github/workflows/dockerhub-description.yml), I keep on receiving the error:

```
Run peter-evans/dockerhub-description@v2.1.0
/usr/bin/docker run --name peterevansdockerhubdescription210_fa0d35 --label e87b52 --workdir /github/workspace --rm -e DOCKERHUB_USERNAME -e DOCKERHUB_PASSWORD -e DOCKERHUB_REPOSITORY -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/private-internet-access-docker/private-internet-access-docker":"/github/workspace" peterevans/dockerhub-description:2.1.0
Acquiring token
Sending PATCH request
Received response code: 400
```

Any idea on how to fix it?

Thanks!

**Comment by peter-evans** [comment]
Hi @qdm12 

After some trial and error reproducing this issue I've figured out the problem. There is upper limit to the data size that the API will allow. The limit seems to be exactly 25,003 bytes. If you send 25,004 bytes you will receive a 400 response.

Unfortunately, there is nothing I can do about this. You will need to reduce the size of your README file, or create a separate short version of the README specifically for Docker Hub.

I will add a note to the documentation about this.

**Comment by qdm12** [comment]
Thanks so much for the quick reply. Text does add up some KB! My readme is indeed 28KB. Maybe you could have your action check the readme file size and return an error/warning if it's bigger than the limit?

**Comment by peter-evans** [comment]
Good idea. I've updated the action to return an error if the file size is larger than 25,000 bytes.

**Comment by qdm12** [comment]
Nice, great job :+1: Have a good weekend!
