### ISSUE TITLE
minor request: catch 'receive response code: 200'

### ISSUE THREAD

**Issue by TrueOsiris** [peter-evans/dockerhub-description#13]
1. Thanks for this container!
2. Just a remark: you could catch the response code 200 & output something like 'upload succeeded'

**Comment by peter-evans** [comment]
Hi @TrueOsiris 

You're right. It might not be clear to all users that `200` means the request was successful. I'll output a clearer message at the end.

**Comment by peter-evans** [comment]
Updated and released. The action now outputs `Request successful` or `Request failed` at the end of execution.
Thanks.
