### ISSUE TITLE
Updating the readme fails with an error

### ISSUE THREAD

**Issue by NotMyFault** [peter-evans/dockerhub-description#193]
Hey,

I am trying to set up this action in a demo repository, but the upload to dockerhub fails.

The GitHub repository: https://github.com/NotMyFault/dockerhub-sync-em
The dockerhub repository: https://hub.docker.com/r/notmyfault1/sync-demo
The error: https://github.com/NotMyFault/dockerhub-sync-em/actions/runs/5718510401/job/15494494754
```
##[debug]Truncated short description: 
Acquiring token
::add-mask::***
Sending PATCH request
##[debug]Error: Not Found
##[debug]    at /home/runner/work/_actions/peter-evans/dockerhub-description/v3/dist/index.js:82:23
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not Found
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Update Docker Hub description
```
Currently, I'm authenticating with a username and password, am I missing something?

Thanks in advance!

**Comment by peter-evans** [comment]
Hi @NotMyFault 

Please take a look at the usage examples:
https://github.com/peter-evans/dockerhub-description#usage

You should use `with`, not `env` to specify inputs. Also check the input names are correct.

```diff
-     env:
+     with:
-       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+       username: ${{ secrets.DOCKERHUB_USERNAME }}
-       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
+       password: ${{ secrets.DOCKERHUB_PASSWORD }}
        enable-url-completion: true
        short-description: ${{ github.event.repository.description }}
        repository: notmyfault1/sync-demo
```

**Comment by NotMyFault** [comment]
Thanks for the pointer!
