### ISSUE TITLE
Permission denied (403)

### ISSUE THREAD

**Issue by xmatthias** [peter-evans/dockerhub-description#2]
When using a organization repository on docker-hub, and using a helper-user to push, this helper-user needs admin-rights (not `read&write`).

This should be mentioned in the documentation - took me a bit to figure out.

**Comment by peter-evans** [comment]
@xmatthias Thank you for letting me know about this. I will add a note about it in the documentation.

**Comment by peter-evans** [comment]
Added a note via this commit https://github.com/peter-evans/dockerhub-description/commit/843595a14f7af3f7753c3558838901c8a1023684
