### ISSUE TITLE
Discrepancy between "successful" message and reality for PATCH request

### ISSUE THREAD

**Issue by webbertakken** [peter-evans/dockerhub-description#22]
I ran a few hundred workflows that all showed successful but did in fact not update the description.

See screenshot or in the [result](https://github.com/Unity-CI/docker/pull/38/checks?check_run_id=1310976486)

![image](https://user-images.githubusercontent.com/20756439/97221635-785c9500-17cd-11eb-9ee1-494bcb7bdc4b.png)

Am I doing something wrong?

Currently I have no way of knowing as the [response](https://github.com/peter-evans/dockerhub-description/blob/dac62d382ae2aaf0ec138c763ec7fe70d50da7fb/src/dockerhub-helper.ts#L36) is not being captured and the [success](https://github.com/peter-evans/dockerhub-description/blob/dac62d382ae2aaf0ec138c763ec7fe70d50da7fb/src/main.ts#L41) message is always showing regardless of the response.

**Comment by peter-evans** [comment]
Hi @webbertakken 

Apologies. This was a bug that I introduced recently due to my misunderstanding about how `node-fetch` works. I've fixed it and released a new version. When you run the action now you should see an error response. Thank you for the report!
