### ISSUE TITLE
Feature request: Allow login using token instead of users password.

### ISSUE THREAD

**Issue by webbertakken** [peter-evans/dockerhub-description#24]
As a followup to #22, which solved the problem of not seeing any error, I'm now [getting](https://github.com/Unity-CI/docker/pull/38/checks?check_run_id=1314153673) response `FORBIDDEN`.

![image](https://user-images.githubusercontent.com/20756439/97503313-1b034800-1975-11eb-933e-79040d29efe7.png)

This is I guess as expected because i'm using a token as the password, which can not be used to acquire a token for obvious reasons. The reason however for using a token and not the password is that tokens are easy to revoke, and also prescribed in `docker/login-action` and  [`docker/docker-push-action`](https://github.com/docker/build-push-action#usage).

For now I will switch to using my users password, but it would be really nice to have the option to use either `password` or `token` as an input. Perhaps it could even auto-detect (say by the number of characters).

**Comment by peter-evans** [comment]
Hi @webbertakken 

Unfortunately there is nothing I can do to support this feature at the moment. Please see this issue: https://github.com/peter-evans/dockerhub-description/issues/10

You can also upvote/follow this issue on the Docker roadmap: https://github.com/docker/roadmap/issues/115

**Comment by webbertakken** [comment]
Thanks for the quick reply @peter-evans. Upvoted the issue. Lets see if their roadmap toward monetisation will help a little bit towards this.
