### ISSUE TITLE
[Help] Getting Error: Forbidden

### ISSUE THREAD

**Issue by jammsen** [peter-evans/dockerhub-description#248]
Hello @peter-evans 
Ive tried your github action and before my readme.md was just to big with 37KB. I was basically successfully getting the 25.000 byte error and it didnt do anyting.

No i have reduced my readme.md considerable, now im getting the "Error: Forbidden" error.

What i tried:
- Comment out enable-url-completion: true
- Added new key, with still read/write/delete rights
- Checked existing for read/write/delete
- re-run the job after like 15m

Im not sure on how to fix this, please help me.

My pipeline-line: https://github.dev/jammsen/docker-palworld-dedicated-server/blob/master/.github/workflows/docker-build-and-push-prod.yml

Error-Screenshot: 
![image](https://github.com/peter-evans/dockerhub-description/assets/2270806/5ffd06fe-47d0-4f80-be20-4d45a7484c4c)

**Comment by peter-evans** [comment]
Hi @jammsen 

You are getting a `403 Forbidden` response from DockerHub, so there is likely something wrong with your inputs, or the token.

**Comment by jammsen** [comment]
Hey @peter-evans 
```yaml
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
Im putting my username in DOCKERHUB_USERNAME and my read/write/delete access token for this in DOCKERHUB_TOKEN

**Comment by jammsen** [comment]
I would be available if you would like to jump on a call and look at it.

**Comment by jammsen** [comment]
@peter-evans is there something wrong with [this](https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/.github/workflows/docker-build-and-push-prod.yml#L61) approach?

**Comment by pmoscode** [comment]
Hi,
I have the same behavior, and I changed nothing. 
From one day to another this happened.

**Comment by jammsen** [comment]
Hey @pmoscode oh hey, yeah i tried on the 30.01 too, didnt work, i tried it now 7 times to create new data and set it up, in my main repo and in a private-test-repo and private-test-docker-hub-repo. No success what so ever. And Peter hasnt answered yet 😭

**Comment by pmoscode** [comment]
Hi @jammsen, @peter-evans,
I think, I found something:
When I create a full PAT (read, write, delete) then it is working. But not with a "just" read & write PAT...
So, due to the fact that I didn't change anything here for years, I assume, DockerHub has changed something. But I don't find any clue on that. A bug on their side could also the the root cause.

**Comment by jammsen** [comment]
Hey @pmoscode - What do you mean by PAT? Do you mean Access-Token?

Mine have both Read-Write-Delete since they have been created:
![image](https://github.com/peter-evans/dockerhub-description/assets/2270806/e13d2210-4694-4f75-8675-f574c3a8d941)

The lower one was created on that day for testing.

**Comment by jammsen** [comment]
@peter-evans Do you have any idea what could be the cause of this?
I pasted the input and tokens multiple times new and the upload of the Docker-Image on Docker-Hub works with them, just not the description.

**Comment by pmoscode** [comment]
> Hey @pmoscode - What do you mean by PAT? Do you mean Access-Token?
> 
> Mine have both Read-Write-Delete since they have been created: ![image](https://private-user-images.githubusercontent.com/2270806/302051063-e13d2210-4694-4f75-8675-f574c3a8d941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODE1ODcsIm5iZiI6MTcwNjk4MTI4NywicGF0aCI6Ii8yMjcwODA2LzMwMjA1MTA2My1lMTNkMjIxMC00Njk0LTRmNzUtODY3NS1mNTc0YzNhOGQ5NDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTcyODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM5YmYwNmY3OGQ4NzNmNzc4Yjg0YzJmYmMzMmFlNTY5ODFkM2U1OGYxMWY1ZWE1ODEyYjAwYWU0NzdmNTZmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U9-E8If-sM4jkaARdn1Yb23xmoMy-GIg6QnY7m3j2OE)
> 
> The lower one was created on that day for testing.

Yes, I mean the Access Token.

**Comment by peter-evans** [comment]
@jammsen The problem is here: https://github.com/jammsen/docker-palworld-dedicated-server/blob/master/.github/workflows/docker-build-and-push-prod.yml#L67

You are pointing to my DockerHub repository, not your own. That's why you are getting 403 Forbidden. Change it to point to your own repository on DockerHub.

@pmoscode Your issue is unrelated. The readme states that you need a `read/write/delete` scoped DockerHub access token.

**Comment by jammsen** [comment]
> @jammsen The problem is here: https://github.com/jammsen/docker-palworld-dedicated-server/blob/master/.github/workflows/docker-build-and-push-prod.yml#L67
> 
> You are pointing to my DockerHub repository, not your own. That's why you are getting 403 Forbidden. Change it to point to your own repository on DockerHub.

Ohhhh thanks so much, i thougth if would be a reference so the github action would be working, i clearly have to read and understand the readme better. Sorry for that!
