### ISSUE TITLE
Docker Hub markdown rendering issue

### ISSUE THREAD

**Issue by hotio** [peter-evans/dockerhub-description#3]
Not sure if you can fix this one, but when the character `<` is found in the README.md the upload stops at that character. No errors are returned (just 200 OK), but the chracter `<` and everything afterwards is missing.

Sample that breaks the upload: https://github.com/hotio/docker-radarr/tree/d2b7b5544a06d70bbe0235ef6a09b8377e1fa26e#execute-scripts-at-startup

**Comment by peter-evans** [comment]
@hotio Thanks for reporting this issue. I'll take a look.

**Comment by peter-evans** [comment]
It looks like this is a markdown rendering issue with Docker Hub itself. The README.md file is being uploaded fully and successfully.

When I tried your sample it appears like this on Docker Hub:
![image](https://user-images.githubusercontent.com/18365890/64667702-a4b43580-d495-11e9-81b7-9b1a1ccc5325.png)

However, if you edit the full description and look at the content, the full contents of the README.md are there.
![image](https://user-images.githubusercontent.com/18365890/64667762-dc22e200-d495-11e9-973b-0778b455c8b7.png)

There is nothing that I can do about this I'm afraid. The only course of action would be to file an issue with Docker Hub.

**Comment by peter-evans** [comment]
If you don't mind I'm going to edit the title of this issue and leave it open for reference until it's fixed by Docker Hub.

**Comment by peter-evans** [comment]
It looks like a known issue. See https://github.com/docker/hub-feedback/issues/1805

**Comment by hotio** [comment]
Thanks, should have looked at this myself more closely....didn't even think about just hitting the Edit button. 😁

**Comment by peter-evans** [comment]
@hotio DockerHub have made a fix and your sample seems to render ok now.

**Comment by peter-evans** [comment]
Closing this issue for now since it appears to be fixed.
