### ISSUE TITLE
Update Dockerfile?

### ISSUE THREAD

**Issue by pjeby** [peter-evans/dockerhub-description#53]
Just started using this since I had to migrate from Docker Hub builds, and discovered that the Dockerfile shown on Docker Hub is out of date on the repos where I'm using this.  Is there any way to update the Dockerfile as well as the README?

**Comment by peter-evans** [comment]
Hi @pjeby 

As far as I know there is no API to push the Dockerfile and update it. I think it's only updated when Docker Hub is configured to pull (Docker Hub builds), which makes sense because it's pulling your repository containing the Dockerfile.

**Comment by pjeby** [comment]
Darn.  Guess I'll have to just include a note in the README on those projects to not trust the Dockerfile shown on Docker Hub.  Thanks anyway.
