### ISSUE TITLE
Not able to use Access token

### ISSUE THREAD

**Issue by kamko** [peter-evans/dockerhub-description#6]
Hello,

we're not able to use docker hub while using [access tokens](https://docs.docker.com/docker-hub/access-tokens/). Is not fault of this action as it's not supported by docker hub.

ref:
https://github.com/docker/hub-feedback/issues/1914

Would be nice if you could add a note about this to the readme.

Nice action idea otherwise.

kj.

**Comment by peter-evans** [comment]
Hi @kamko 

I've updated the readme so this doesn't catch people out. Hopefully Docker Hub will introduce scopes to allow this in future.

Thank you!
