### ISSUE TITLE
Permissions for access tokens

### ISSUE THREAD

**Issue by wilmhit** [peter-evans/dockerhub-description#68]
Hello,
I would like to requests an inclusion of needed permission in README file.

As user fauust pointed out in issue #10 access tokens must have read/write/delete access level in order to work. This took me quite a while to pinpoint. Neither this project's documentation or docker settings do a good job of pointing that out. It would be great if that was explained in readme.

**Comment by peter-evans** [comment]
Added. Thanks!

https://github.com/peter-evans/dockerhub-description/commit/22ceabb3905c27acaa0300af8cfe7d7741d3e84e
