### ISSUE TITLE
Always Getting Forbidden When Using This Action

### ISSUE THREAD

**Issue by y0utubeperson1** [peter-evans/dockerhub-description#70]
I am trying to setup GitHub Actions to update my Dockerhub's Repo Description.

So far, my GitHub Actions can log in and update the image without issue (I use "_docker/build-push-action@v3_" to update my Docker Image). But I cannot update the image description

See one of my actions: https://github.com/y0utubeperson1/test-dock1/runs/7591832228?check_suite_focus=true#step:13:13

This is my Actions YAML file: https://github.com/y0utubeperson1/test-dock1/blob/main/.github/workflows/test_dockerfile.yml

My Image on Docker Hub: https://hub.docker.com/repository/docker/y0utubesir/mytestimg

I am using Docker Tokens.

How come I can successfully update my image but not description?

**Comment by y0utubeperson1** [comment]
Solved, didnt have DELETE permission in token.

**Comment by miparnisari** [comment]
why does it need the `DELETE` permission? @peter-evans can you document this in the README please?

**Comment by peter-evans** [comment]
@miparnisari It is documented in the readme already.

> (required) Docker Hub password or [Personal Access Token](https://docs.docker.com/docker-hub/access-tokens/) with `read/write/delete` scope.

https://github.com/peter-evans/dockerhub-description#action-inputs

I don't really know why it needs the `read/write/delete` scope. I guess it's the equivalent of "admin" which seems to be required for modifying Docker repository descriptions.

**Comment by miparnisari** [comment]
> It is documented in the readme already.

ah yeah sorry 😅  I meant documenting why it needs the `delete` permission.

The code doing the update is 

https://github.com/peter-evans/dockerhub-description/blob/579f64ca0abced29dbbc44ab4c6a0b9e33ab3588/src/dockerhub-helper.ts#L39-L46

I can't find documentation for this API

**Comment by peter-evans** [comment]
I don't think there is any public documentation for this API. At least, there wasn't when I first created this action. I discovered it by finding other tools and open source code that was using it.

If you want answers about why it needs the `read/write/delete` scope then please try asking the folks at Docker. As I mentioned before, my guess is that `read/write/delete` is considered "admin" level permission, which is what they seem to require for modifying the description of a repository. It kind of makes sense when you consider that `write` means "permission to push Docker images" not "permission to change the repository description."

**Comment by miparnisari** [comment]
Asked in https://github.com/docker/hub-feedback/issues/2321
