### ISSUE TITLE
Version tags are not correctly pushed to docker hub

### ISSUE THREAD

**Issue by knorrest** [peter-evans/dockerhub-description#78]
Version tags are not correctly pushed to docker hub. The reason is that the GitHub workflow uses only `docker push [IMAGE]` and thus pushes just the default tag, ie `latest`.

**Comment by peter-evans** [comment]
Hi @knorrest 

Thank you for pointing this out! For some reason I thought it was pushing all tags by default. I wonder if the behaviour of the command has changed. 🤔 Anyway, I appreciate your effort to fix it, but I committed my own small fix [here](https://github.com/peter-evans/dockerhub-description/commit/3103d1465d6dacc01d2a4af05429929d0925d5c7). Just adding the flag `--all-tags` is enough.
