### ISSUE TITLE
Use dockerhub PAT to update description

### ISSUE THREAD

**Issue by whizzzkid** [peter-evans/dockerhub-description#90]
Looks like the team made progress a few months ago to allow updating description using PAT: https://github.com/docker/hub-feedback/issues/2127

I think this can now be used to update descriptions.

**Comment by peter-evans** [comment]
Hi @whizzzkid 

Yes, I already updated the readme to reflect that you can now use a [Personal Access Token](https://docs.docker.com/docker-hub/access-tokens/) with read/write/delete scope.
